import type {
  Unit,
  ValidationRule,
  RawData,
  Validation,
  Remittance,
  RemittanceLog,
  AuditLog,
  EndpointConfig,
  User,
  RemittanceStats,
} from '@/types';

// Mock User
export const mockUser: User = {
  id: '1',
  name: 'Admin Sistema',
  email: 'admin@exemplo.gov.br',
  role: 'ADMIN',
  avatar: undefined,
};

// Mock Units
export const mockUnits: Unit[] = [
  {
    id: '1',
    code: '090101',
    name: 'Secretaria de Administração',
    tokenProducao: 'token-prod-xxx',
    tokenHomologacao: 'token-hom-xxx',
    ambiente: 'HOMOLOGACAO',
    active: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    code: '090102',
    name: 'Secretaria de Fazenda',
    tokenProducao: 'token-prod-yyy',
    tokenHomologacao: 'token-hom-yyy',
    ambiente: 'PRODUCAO',
    active: true,
    createdAt: '2024-01-20T14:30:00Z',
  },
  {
    id: '3',
    code: '090103',
    name: 'Secretaria de Saúde',
    ambiente: 'HOMOLOGACAO',
    active: false,
    createdAt: '2024-02-01T09:00:00Z',
  },
];

// Mock Validation Rules
export const mockValidationRules: ValidationRule[] = [
  {
    id: '1',
    module: 'CONTRATO',
    field: 'valor',
    operator: 'GREATER_THAN',
    value: '0',
    level: 'IMPEDITIVA',
    code: 'CT001',
    message: 'O valor do contrato deve ser maior que zero',
    active: true,
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: '2',
    module: 'CONTRATO',
    field: 'objeto',
    operator: 'IS_NOT_NULL',
    value: '',
    level: 'IMPEDITIVA',
    code: 'CT002',
    message: 'O objeto do contrato é obrigatório',
    active: true,
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: '3',
    module: 'COMPRA_DIRETA',
    field: 'justificativa',
    operator: 'IS_NOT_NULL',
    value: '',
    level: 'ALERTA',
    code: 'CD001',
    message: 'Recomenda-se informar a justificativa da compra direta',
    active: true,
    createdAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '4',
    module: 'EMPENHO',
    field: 'dotacao',
    operator: 'REGEX',
    value: '^\\d{2}\\.\\d{3}\\.\\d{4}\\.\\d{4}$',
    level: 'IMPEDITIVA',
    code: 'EP001',
    message: 'A dotação orçamentária está em formato inválido',
    active: true,
    createdAt: '2024-01-15T11:00:00Z',
  },
  {
    id: '5',
    module: 'PAGAMENTO',
    field: 'dataVencimento',
    operator: 'IS_NOT_NULL',
    value: '',
    level: 'ALERTA',
    code: 'PG001',
    message: 'Data de vencimento não informada',
    active: false,
    createdAt: '2024-01-18T09:00:00Z',
  },
];

// Mock Raw Data
export const mockRawData: RawData[] = [
  {
    id: '1',
    unitId: '1',
    unit: mockUnits[0],
    module: 'CONTRATO',
    competency: '2024-12',
    payload: {
      numero: '001/2024',
      objeto: 'Aquisição de equipamentos de informática',
      valor: 150000,
      dataInicio: '2024-01-01',
      dataFim: '2024-12-31',
      contratado: {
        cnpj: '12.345.678/0001-90',
        razaoSocial: 'Tech Solutions Ltda',
      },
    },
    status: 'PROCESSED',
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: '2',
    unitId: '1',
    unit: mockUnits[0],
    module: 'EMPENHO',
    competency: '2024-12',
    payload: {
      numero: '2024NE00001',
      dotacao: '02.001.0401.2001',
      valor: 50000,
      credor: 'Fornecedor ABC',
    },
    status: 'PROCESSING',
    createdAt: '2024-12-02T14:30:00Z',
  },
  {
    id: '3',
    unitId: '2',
    unit: mockUnits[1],
    module: 'COMPRA_DIRETA',
    competency: '2024-12',
    payload: {
      numero: 'CD001/2024',
      objeto: 'Material de escritório',
      valor: 8000,
      modalidade: 'DISPENSA',
    },
    status: 'RECEIVED',
    createdAt: '2024-12-03T08:00:00Z',
  },
  {
    id: '4',
    unitId: '1',
    unit: mockUnits[0],
    module: 'LIQUIDACAO',
    competency: '2024-11',
    payload: {
      empenho: '2024NE00001',
      valor: 25000,
      documento: 'NF-e 123456',
    },
    status: 'ERROR',
    createdAt: '2024-11-28T16:00:00Z',
  },
];

// Mock Validations
export const mockValidations: Validation[] = [
  {
    id: '1',
    rawDataId: '1',
    ruleId: '1',
    level: 'IMPEDITIVA',
    code: 'CT001',
    message: 'O valor do contrato deve ser maior que zero',
    field: 'valor',
    value: '150000',
    createdAt: '2024-12-01T10:05:00Z',
  },
  {
    id: '2',
    rawDataId: '4',
    ruleId: '4',
    level: 'IMPEDITIVA',
    code: 'EP001',
    message: 'A dotação orçamentária está em formato inválido',
    field: 'dotacao',
    value: 'INVALID',
    createdAt: '2024-11-28T16:05:00Z',
  },
];

// Mock Remittances
export const mockRemittances: Remittance[] = [
  {
    id: '1',
    unitId: '1',
    unit: mockUnits[0],
    rawDataId: '1',
    module: 'CONTRATO',
    competency: '2024-12',
    status: 'SENT',
    payload: {
      tipoRemessa: 'CONTRATO',
      dados: { numero: '001/2024', valor: 150000 },
    },
    protocol: 'TCE-2024-001234',
    createdAt: '2024-12-01T11:00:00Z',
    sentAt: '2024-12-01T11:05:00Z',
  },
  {
    id: '2',
    unitId: '1',
    unit: mockUnits[0],
    rawDataId: '2',
    module: 'EMPENHO',
    competency: '2024-12',
    status: 'READY',
    payload: {
      tipoRemessa: 'EMPENHO',
      dados: { numero: '2024NE00001', valor: 50000 },
    },
    createdAt: '2024-12-02T15:00:00Z',
  },
  {
    id: '3',
    unitId: '2',
    unit: mockUnits[1],
    rawDataId: '3',
    module: 'COMPRA_DIRETA',
    competency: '2024-12',
    status: 'PENDING',
    payload: {},
    createdAt: '2024-12-03T08:30:00Z',
  },
  {
    id: '4',
    unitId: '1',
    unit: mockUnits[0],
    rawDataId: '4',
    module: 'LIQUIDACAO',
    competency: '2024-11',
    status: 'ERROR',
    payload: { tipoRemessa: 'LIQUIDACAO', dados: {} },
    errorMsg: 'Erro de validação: dotação inválida',
    createdAt: '2024-11-28T17:00:00Z',
  },
  {
    id: '5',
    unitId: '1',
    unit: mockUnits[0],
    rawDataId: '1',
    module: 'CONTRATO',
    competency: '2024-11',
    status: 'SENDING',
    payload: { tipoRemessa: 'CONTRATO', dados: {} },
    createdAt: '2024-11-30T09:00:00Z',
  },
  {
    id: '6',
    unitId: '2',
    unit: mockUnits[1],
    rawDataId: '2',
    module: 'PAGAMENTO',
    competency: '2024-12',
    status: 'CANCELLED',
    payload: {},
    createdAt: '2024-12-01T08:00:00Z',
  },
];

// Mock Remittance Logs
export const mockRemittanceLogs: RemittanceLog[] = [
  {
    id: '1',
    remittanceId: '1',
    direction: 'REQUEST',
    url: '/api/v1/remessas',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Bearer xxx',
    },
    body: { tipoRemessa: 'CONTRATO', dados: {} },
    createdAt: '2024-12-01T11:05:00Z',
  },
  {
    id: '2',
    remittanceId: '1',
    direction: 'RESPONSE',
    url: '/api/v1/remessas',
    method: 'POST',
    statusCode: 200,
    headers: { 'Content-Type': 'application/json' },
    body: { protocolo: 'TCE-2024-001234', status: 'RECEBIDO' },
    duration: 1250,
    createdAt: '2024-12-01T11:05:01Z',
  },
  {
    id: '3',
    remittanceId: '4',
    direction: 'REQUEST',
    url: '/api/v1/remessas',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: 'Bearer xxx',
    },
    body: { tipoRemessa: 'LIQUIDACAO', dados: {} },
    createdAt: '2024-11-28T17:00:00Z',
  },
  {
    id: '4',
    remittanceId: '4',
    direction: 'RESPONSE',
    url: '/api/v1/remessas',
    method: 'POST',
    statusCode: 400,
    headers: { 'Content-Type': 'application/json' },
    body: { error: 'Validação falhou', details: ['Dotação inválida'] },
    duration: 850,
    createdAt: '2024-11-28T17:00:01Z',
  },
];

// Mock Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    entity: 'Unit',
    entityId: '1',
    action: 'CREATE',
    user: 'admin@exemplo.gov.br',
    ip: '192.168.1.100',
    // newValue: mockUnits[0],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    entity: 'ValidationRule',
    entityId: '1',
    action: 'CREATE',
    user: 'admin@exemplo.gov.br',
    ip: '192.168.1.100',
    // newValue: mockValidationRules[0],
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: '3',
    entity: 'Remittance',
    entityId: '1',
    action: 'SEND',
    user: 'Sistema',
    ip: '127.0.0.1',
    oldValue: { status: 'READY' },
    newValue: { status: 'SENT', protocol: 'TCE-2024-001234' },
    createdAt: '2024-12-01T11:05:00Z',
  },
  {
    id: '4',
    entity: 'Unit',
    entityId: '3',
    action: 'UPDATE',
    user: 'admin@exemplo.gov.br',
    ip: '192.168.1.100',
    oldValue: { active: true },
    newValue: { active: false },
    createdAt: '2024-02-15T14:00:00Z',
  },
];

// Mock Endpoint Configs
export const mockEndpointConfigs: EndpointConfig[] = [
  {
    id: '1',
    module: 'CONTRATO',
    endpoint: '/api/v1/contratos',
    method: 'POST',
    active: true,
    description: 'Endpoint para envio de dados de contratos',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    module: 'EMPENHO',
    endpoint: '/api/v1/empenhos',
    method: 'POST',
    active: true,
    description: 'Endpoint para envio de dados de empenhos',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    module: 'COMPRA_DIRETA',
    endpoint: '/api/v1/compras-diretas',
    method: 'POST',
    active: true,
    description: 'Endpoint para envio de compras diretas',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    module: 'LIQUIDACAO',
    endpoint: '/api/v1/liquidacoes',
    method: 'POST',
    active: false,
    description: 'Endpoint para envio de liquidações (desativado)',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Stats
export const mockRemittanceStats: RemittanceStats = {
  total: 6,
  byStatus: {
    PENDING: 1,
    VALIDATING: 0,
    TRANSFORMING: 0,
    READY: 1,
    SENDING: 1,
    SENT: 1,
    ERROR: 1,
    CANCELLED: 1,
  },
  errorsLast24h: 1,
  lastProtocol: 'TCE-2024-001234',
  lastProtocolDate: '2024-12-01T11:05:00Z',
};
